[project]
name = "infraestructura-publica-cl"
version = "0.1.0"
description = "Plataforma de datos sobre la cartera de inversión pública en Chile (BIP)"
readme = "README.md"
authors = [
    { name = "Rafael Godoy", email = "204746951+RafaelGodoy98@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
